#!/usr/bin/env python3
"""Write .github/workflows/evergif.yml, which keeps the demo GIF fresh.

Usage: ci.py [--setup "pip install -e ."] [--setup "..."] [--branch main]
             [--cron "0 6 * * 1"] [--tape demo/evergif.tape]
             [--gif demo/evergif.gif] [--out PATH] [--force] [--stdout]

The workflow re-renders the tape on push to the default branch and weekly, and
opens a PR only when the rendered GIF's frames differ from the committed one.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

TEMPLATE = Path(__file__).resolve().parent.parent / "assets" / "evergif-workflow.yml.tmpl"
HEADER = ("# Generated by evergif (https://github.com/ShreyasDasari/evergif).\n"
          "# Keeps the README demo GIFs in sync with the CLI.\n")
CRON = re.compile(r"^(\S+\s+){4}\S+$")


def default_branch() -> str:
    for args in (["git", "symbolic-ref", "--short", "refs/remotes/origin/HEAD"],
                 ["git", "branch", "--show-current"]):
        try:
            result = subprocess.run(args, capture_output=True, text=True, timeout=10)
        except (OSError, subprocess.TimeoutExpired):
            continue
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().rsplit("/", 1)[-1]
    return "main"


def render(args: argparse.Namespace) -> str:
    setup = args.setup or ['echo "no setup needed"']
    steps = "\n".join(f"          {line}" for line in setup)
    body = TEMPLATE.read_text(encoding="utf-8")
    for token, value in (("__EVERGIF_SETUP__", steps),
                         ("__EVERGIF_BRANCH__", args.branch or default_branch()),
                         ("__EVERGIF_CRON__", args.cron)):
        body = body.replace(token, value)
    return HEADER + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--setup", action="append", default=[],
                        help="shell line to prepare the project in CI (repeatable)")
    parser.add_argument("--branch", default=None, help="default: this repo's branch")
    parser.add_argument("--cron", default="0 6 * * 1", help="weekly re-render schedule")
    parser.add_argument("--out", default=".github/workflows/evergif.yml")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing workflow that evergif did not write")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    if not CRON.match(args.cron):
        print(f"error: --cron must have 5 fields: {args.cron!r}", file=sys.stderr)
        return 2
    for line in args.setup:
        if "\n" in line:
            print("error: --setup takes one line; repeat the flag for more",
                  file=sys.stderr)
            return 2
    tapes = sorted(Path("demo").glob("*.tape")) if Path("demo").is_dir() else []
    if not tapes:
        print("warning: no demo/*.tape yet; run tape.py first", file=sys.stderr)
    else:
        print("covers: " + ", ".join(t.stem for t in tapes))

    workflow = render(args)
    if args.stdout:
        sys.stdout.write(workflow)
        return 0
    out = Path(args.out)
    if out.is_file() and "Generated by evergif" not in out.read_text(encoding="utf-8") \
            and not args.force:
        print(f"error: {out} exists and was not written by evergif; "
              "pass --force to overwrite", file=sys.stderr)
        return 2
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(workflow, encoding="utf-8")
    print(f"wrote {out}")
    print("enable Settings > Actions > General > "
          "'Allow GitHub Actions to create and approve pull requests'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
