#!/usr/bin/env python3
"""Write the GitHub workflows that keep the demo GIFs fresh.

Usage: ci.py [--setup "pip install -e ."] [--setup "..."] [--branch main]
             [--cron "0 6 * * 1"] [--pr] [--no-cloud] [--force] [--stdout]

Two workflows are written:

  evergif.yml          on push, weekly and on demand, re-runs each demo's
                       recorded commands, compares a hash of their output
                       against demo/<name>.lock, and re-renders only the demos
                       whose output changed. The refreshed GIFs are committed
                       straight to the branch, which needs no repository
                       settings; --pr opens a pull request instead.
  evergif-render.yml   renders demo GIFs in CI, so a contributor with no local
                       toolchain can edit a tape and let CI produce the GIF.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "assets"
FRESHNESS = ASSETS / "evergif-workflow.yml.tmpl"
CLOUD = ASSETS / "evergif-render-workflow.yml.tmpl"
HEADER = "# Generated by evergif (https://github.com/ShreyasDasari/evergif).\n"
CRON = re.compile(r"^(\S+\s+){4}\S+$")


def default_branch() -> str:
    for args in (["git", "symbolic-ref", "--short", "refs/remotes/origin/HEAD"],
                 ["git", "branch", "--show-current"]):
        try:
            result = subprocess.run(args, capture_output=True, text=True, timeout=10)
        except (OSError, subprocess.TimeoutExpired):
            continue
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().rsplit("/", 1)[-1]
    return "main"


def select_blocks(body: str, keep: str) -> str:
    """Emit only the chosen delivery block, so the workflow ships clean.

    The template marks alternatives with `#<<name` ... `#name>>`; the block
    that is not selected is removed entirely rather than left disabled.
    """
    for name in ("commit", "pr"):
        pattern = rf"[ \t]*#<<{name}\n(.*?)[ \t]*#{name}>>\n"
        replacement = (lambda m: m.group(1)) if name == keep else ""
        body = re.sub(pattern, replacement, body, flags=re.DOTALL)
    return body


def render(template: Path, args: argparse.Namespace, branch: str) -> str:
    setup = args.setup or ['echo "no setup needed"']
    steps = "\n".join(f"          {line}" for line in setup)
    body = template.read_text(encoding="utf-8")
    for token, value in (("__EVERGIF_SETUP__", steps),
                         ("__EVERGIF_BRANCH__", branch),
                         ("__EVERGIF_CRON__", args.cron)):
        body = body.replace(token, value)
    return HEADER + select_blocks(body, "pr" if args.pr else "commit")


def write(out: Path, body: str, force: bool) -> bool:
    if out.is_file() and "Generated by evergif" not in out.read_text(encoding="utf-8") \
            and not force:
        print(f"error: {out} exists and was not written by evergif; "
              "pass --force to overwrite", file=sys.stderr)
        return False
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--setup", action="append", default=[],
                        help="shell line to prepare the project in CI (repeatable)")
    parser.add_argument("--branch", default=None, help="default: this repo's branch")
    parser.add_argument("--cron", default="0 6 * * 1", help="weekly re-render schedule")
    parser.add_argument("--out", default=".github/workflows/evergif.yml")
    parser.add_argument("--pr", action="store_true",
                        help="open a PR instead of committing the refreshed GIFs; "
                             "needs 'Allow GitHub Actions to create and approve "
                             "pull requests' in the repository settings")
    parser.add_argument("--cloud-out", default=".github/workflows/evergif-render.yml")
    parser.add_argument("--no-cloud", action="store_true",
                        help="skip the render-in-CI workflow")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing workflow that evergif did not write")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    if not CRON.match(args.cron):
        print(f"error: --cron must have 5 fields: {args.cron!r}", file=sys.stderr)
        return 2
    for line in args.setup:
        if "\n" in line:
            print("error: --setup takes one line; repeat the flag for more",
                  file=sys.stderr)
            return 2
    tapes = sorted(Path("demo").glob("*.tape")) if Path("demo").is_dir() else []
    if not tapes:
        print("warning: no demo/*.tape yet; run tape.py first", file=sys.stderr)
    else:
        print("covers: " + ", ".join(t.stem for t in tapes))

    branch = args.branch or default_branch()
    freshness = render(FRESHNESS, args, branch)
    if args.stdout:
        sys.stdout.write(freshness)
        return 0
    if not write(Path(args.out), freshness, args.force):
        return 2
    if not args.no_cloud and not write(Path(args.cloud_out),
                                       render(CLOUD, args, branch), args.force):
        return 2
    if args.pr:
        print("--pr needs Settings > Actions > General > 'Allow GitHub Actions "
              "to create and approve pull requests' (off by default)")
    else:
        print("refreshed GIFs are committed straight to the branch; "
              "no repository settings needed")
    if not args.no_cloud:
        print("contributors without vhs can now edit a tape, open a PR, and let "
              "CI render the GIF for them")
    return 0


if __name__ == "__main__":
    sys.exit(main())
